# Generated by Django 3.1.4 on 2021-01-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('formation', models.CharField(max_length=30)),
                ('etat', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=5, verbose_name='Actif')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('public', models.CharField(blank=True, max_length=30, null=True)),
                ('dure', models.CharField(max_length=30, verbose_name='Durée')),
                ('thematique', models.CharField(blank=True, max_length=20, null=True, verbose_name='thématique')),
                ('profil', models.CharField(blank=True, max_length=30, null=True, verbose_name='Profil utilisateur')),
                ('domaine', models.CharField(blank=True, max_length=30, null=True, verbose_name='Domaine')),
                ('presentation', models.TextField()),
                ('objectif', models.TextField()),
                ('pre_requis', models.TextField()),
                ('program', models.TextField()),
                ('modalite', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de debut')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('start_hours', models.TimeField(verbose_name='Heure de debut')),
                ('end_hours', models.TimeField(verbose_name='Heure de fin')),
                ('lieu', models.CharField(max_length=50, verbose_name='Lieu')),
                ('capacity', models.CharField(max_length=50, verbose_name="Capacité d'accueil")),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(blank=True, max_length=30, null=True)),
                ('entreprise', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('telephone', models.CharField(max_length=20)),
                ('demande', models.TextField()),
                ('nb_person', models.PositiveIntegerField(verbose_name='Nombre de personne à former')),
                ('session', models.CharField(choices=[('SESSION JANVIER 2021', 'SESSION JANVIER 2021'), ('SESSION FEVRIER 2021', 'SESSION FEVRIER 2021')], max_length=20, verbose_name='Session de la formation')),
                ('financement', models.CharField(choices=[('Entreprise', 'Entreprise'), ('Organisme de financement', 'Organisme de financement'), ('Personnel', 'Personnel')], max_length=30, verbose_name='Financement')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.formation')),
            ],
        ),
    ]
